__init__.py, metadata.txt, sammo.py, src/__init__.py, src/gui/__init__.py, src/gui/session.py
=> T1 mise en place plugin

src/core/__init__.py, src/core/database.py, src/core/session.py, src/gui/session.py
- I prevent from adding the geopackage if it already exists in the project
- I choose "session datas" as default layer name. You can change it in database.py L23
=> T2 session creation

src/core/database.py, src/core/session.py
- The gps table is loaded when session starts and displayed in the layer list. What to do if a "gps" layer already exists in the layer list ?
=> T011 gps table creation

.gitignore, Makefile, metadata.txt
Ajoute une fonction d'archivage dans le Makefile, afin de livrer le plugin
=> Archive makefile

sammo.py, src/core/sound_recording_controller.py, src/core/thread_widget.py, src/gui/status_dock.py, src/gui/widget.py, src/gui/widget.ui
The style has to be improved but all is functional except for the following :
When I reload the plugin, a new widget is systematically created. With the _isDockWidgetExists() method in the Widget class, I tried to detect an existing widget but it doesn't work ; so I disabled the call in the line #36 and we have to manually hide the old widgets after each reload. May be you will have an idea.
Of course, the client won't reload the plugin so it is not that important.
=> T026 status widget

src/core/session.py
=> Translation fix

sammo.py, src/core/session.py
add constraint on glareFrom and glareTo attribute
=> glare_dir_constraint

sammo.py
Environment and followers tab should be visible
=> Display several tab

sammo.py, src/core/database.py, src/core/session.py, src/core/sound_recording_controller.py, src/core/thread_simu_gps.py, src/gui/status.py
=> Sighting conf

sammo.py, src/core/database.py, src/core/session.py, src/core/sound_recording_controller.py, src/core/thread_simu_gps.py, src/gui/status.py
Reverts hytechimaging/sammo-boat#83
=> Revert "Sighting conf"

sammo.py, src/core/database.py, src/core/session.py, src/core/sound_recording_controller.py
Update follower form configuration, and add sound record for follower with a delay of 5min as requested
=> followers config + sound added

sammo.py, src/core/session.py, src/gui/effort.py
=> Effort mode

sammo.py, src/core/session.py
Avoid unexplained pushError on adding effort entity
=> avoid unexplained pushError

sammo.py, src/core/database.py, src/core/session.py, src/core/sound_recording_controller.py, src/core/thread_simu_gps.py, src/gui/status.py
https://github.com/hytechimaging/sammo-boat/pull/72
=> Fix simu and flake8

sammo.py
https://github.com/hytechimaging/sammo-boat/pull/73
=> Map follow last gps position

src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/74
=> Side field in sighting form

src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/75
=> Max angle 360

src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/81
=> Optional observer in effort form

src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/81
=> Mask sound file

sammo.py, src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/80
=> glareSever constraint

src/core/session.py
https://github.com/hytechimaging/sammo-boat/pull/86
=> Update sighting conf

sammo.py, src/core/database.py, src/core/session.py, src/core/sound_recording_controller.py
https://github.com/hytechimaging/sammo-boat/pull/87
=> Add sound for followers

src/core/session.py
=> Fix qgis 3.16 ltr

src/core/layers/gps.py, src/core/session.py
@pblottiere To fix the geometry as mentionned in this [comment](https://github.com/hytechimaging/sammo-boat/pull/104#discussion_r769394747)
=> fix geometry on sightings and followers

Makefile, metadata.txt
=> change version

Makefile, metadata.txt, src/core/session.py
=> fix typing

sammo.py, src/core/database.py, src/core/layers/environment.py, src/core/layers/followers.py, src/core/layers/sightings.py, src/core/session.py, src/gui/followers.py
@pblottiere 
project modification + change record time + change on duplicate last feature
=> project modification

CHANGELOG.md, Makefile, metadata.txt
=> prep v1.1.2

CHANGELOG.md, src/core/database.py, src/core/layers/followers.py, src/core/layers/layer.py, src/core/layers/sightings.py, src/core/layers/world.py, src/core/session.py, src/core/utils.py
Ressources as SVG and world map are saved into the db
=> Embbeded ressources

sammo.py, src/core/gps.py, src/core/session.py, src/gui/status.py
The GPRMC frame is not as reliable as the GPGGA frame and may be only received once in a while (especially with the old serial GPS device).
=> Fixes GPS 

src/gui/table.py
A little change for a better use of dockwidget area in sammo-boat
=> change corner for sammotabledock

sammo.py, src/gui/merge.py
FIX #162 
@pblottiere 
Indeed the current session was in conflict with merge (and also if a new session is created when a session is already loaded). I close the current project to avoid conflict, and futhermore the merged session is open after merge process.
=> fix crash on merge

src/core/layers/audio_action.py
Related to #159 but maybe not solving it
@pblottiere I added a check to verify stream attribute, but I don't think the problem is here.
=> add a check to avoid crash

CHANGELOG.md, src/gui/status.py
=> fix status effort

src/core/session.py
=> fix plateform value for first line

src/core/gps.py, src/core/layers/layer.py, src/core/session.py
This PR :
- fixes observer value during validation
- add administration table to merge
- pseudo validation before merge to transfer value from administration table to environment/sighting/followers table
=> Fix observer value + add administrator table to merge

src/core/layers/environment.py, src/core/session.py
=> Enable plateform combobox, including old session

README.md, sammo.py
This MR add an explicit zoom shorcut, needed for the operator mode
=> Zoom shorcut

src/core/gps.py
Fixes some troubles about internal gps that doesn't use 4800 baudrate and doesn't provide GPGGA/GPRMC
=> Management of unpredicted GPS

src/core/session.py, src/gui/merge.py, src/gui/ui/merge.ui
Allow to keep only gps point from one side.
=> Add checkbox for each session to choose gps in merge
